from webdnn.backend.webgl.optimize_rules.split_texture.operators.split_concat import split_concat
from webdnn.backend.webgl.optimize_rules.split_texture.operators.split_im2col import split_im2col
from webdnn.backend.webgl.optimize_rules.split_texture.operators.split_partial_im2col import split_partial_im2col
from webdnn.backend.webgl.optimize_rules.split_texture.operators.split_pooling_2d import split_pooling_2d
from webdnn.backend.webgl.optimize_rules.split_texture.operators.split_reshape import split_reshape
from webdnn.backend.webgl.optimize_rules.split_texture.operators.split_splitaxis import split_splitaxis
from webdnn.backend.webgl.optimize_rules.split_texture.operators.split_tensordot import split_tensordot
from webdnn.backend.webgl.optimize_rules.split_texture.operators.split_tensorwise import split_tensorwise
