from webdnn.backend.webgl.optimize_rules.simplify_channel_mode_conversion import simplify_channel_mode_conversion
from webdnn.backend.webgl.optimize_rules.simplify_channel_mode_conversion import simplify_nonsense_channel_mode_conversion
from webdnn.backend.webgl.optimize_rules.simplify_channel_mode_conversion import simplify_redundant_channel_mode_conversion
