export const initialize_layer: string;
export const initializeLayer: string;
export const layer: string;
export const navbar: string;
export const title: string;
export const message: string;
export const progress: string;
export const progressOuter: string;
export const progressInner: string;
