import os

OPTIMIZE = os.environ.get("OPTIMIZE", "1") == "1"

# optimize rule
CONCAT_ELEMENTWISE_OPERATION = OPTIMIZE and os.environ.get("CONCAT_ELEMENTWISE_OPERATION", "1") == "1"
CONCAT_CHANNELWISE_OPERATION = OPTIMIZE and os.environ.get("CONCAT_CHANNELWISE_OPERATION", "1") == "1"
REMOVE_LAST_SOFTMAX = OPTIMIZE and os.environ.get("REMOVE_LAST_SOFTMAX", "0") == "1"
CONCAT_AFFINE = OPTIMIZE and os.environ.get("CONCAT_AFFINE", "1") == "1"
CONCAT_SGEMM_BIAS = OPTIMIZE and os.environ.get("CONCAT_SGEMM_BIAS", "1") == "1"
CONCAT_SCALAR_OPERATION = OPTIMIZE and os.environ.get("CONCAT_SCALAR_AFFINE", "1") == "1"
INJECT_INLINE_INPLACE = OPTIMIZE and os.environ.get("INJECT_INLINE_INPLACE", "1") == "1"

# memory allocation
VALIDATE_GENERATED_SOURCE = os.environ.get("VALIDATE_GENERATED_SOURCE", "1") == "1"
OPTIMIZE_INPLACE_OPERATION = OPTIMIZE and os.environ.get("OPTIMIZE_INPLACE_OPERATION", "1") == "1"
OPTIMIZE_MEMORY_ALLOCATION = OPTIMIZE and os.environ.get("OPTIMIZE_MEMORY_ALLOCATION", "1") == "1"
