from webdnn.backend.webassembly.optimize_rules import insert_transpose
from webdnn.backend.webassembly.optimize_rules import optimize_sgemm_eigen
from webdnn.backend.webassembly.optimize_rules import webassembly_optimize_rule
