from webdnn.frontend.tensorflow.ops import gen_array_ops
from webdnn.frontend.tensorflow.ops import gen_bitwise_ops
from webdnn.frontend.tensorflow.ops import gen_candidate_sampling_ops
from webdnn.frontend.tensorflow.ops import gen_control_flow_ops
from webdnn.frontend.tensorflow.ops import gen_ctc_ops
from webdnn.frontend.tensorflow.ops import gen_data_flow_ops
from webdnn.frontend.tensorflow.ops import gen_dataset_ops
from webdnn.frontend.tensorflow.ops import gen_functional_ops
from webdnn.frontend.tensorflow.ops import gen_image_ops
from webdnn.frontend.tensorflow.ops import gen_io_ops
from webdnn.frontend.tensorflow.ops import gen_linalg_ops
from webdnn.frontend.tensorflow.ops import gen_logging_ops
from webdnn.frontend.tensorflow.ops import gen_lookup_ops
from webdnn.frontend.tensorflow.ops import gen_math_ops
from webdnn.frontend.tensorflow.ops import gen_nn_ops
from webdnn.frontend.tensorflow.ops import gen_parsing_ops
from webdnn.frontend.tensorflow.ops import gen_random_ops
from webdnn.frontend.tensorflow.ops import gen_resource_variable_ops
from webdnn.frontend.tensorflow.ops import gen_script_ops
from webdnn.frontend.tensorflow.ops import gen_sdca_ops
from webdnn.frontend.tensorflow.ops import gen_set_ops
from webdnn.frontend.tensorflow.ops import gen_sparse_ops
from webdnn.frontend.tensorflow.ops import gen_spectral_ops
from webdnn.frontend.tensorflow.ops import gen_state_ops
from webdnn.frontend.tensorflow.ops import gen_string_ops
from webdnn.frontend.tensorflow.ops import gen_user_ops
