import os

CONCAT_ELEMENTWISE_OPERATION = os.environ.get("FLAG_CONCAT_ELEMENTWISE_OPERATION", "1") == 1
CONCAT_CHANNELWISE_OPERATION = os.environ.get("FLAG_CONCAT_CHANNELWISE_OPERATION", "1") == 1
REMOVE_LAST_SOFTMAX = os.environ.get("FLAG_REMOVE_LAST_SOFTMAX", "1") == 1
AFFINE_CONCAT = os.environ.get("FLAG_AFFINE_CONCAT", "1") == 1
EMBED_METABUFFER_VALUE = os.environ.get("FLAG_EMBED_METABUFFER_VALUE", "0") == 1
