import os

OPTIMIZE = os.environ.get("OPTIMIZE", "1") == "1"

# optimize rule
CONCAT_ELEMENTWISE_OPERATION = OPTIMIZE and os.environ.get("CONCAT_ELEMENTWISE_OPERATION", "1") == "1"
CONCAT_CHANNELWISE_OPERATION = OPTIMIZE and os.environ.get("CONCAT_CHANNELWISE_OPERATION", "1") == "1"
REMOVE_LAST_SOFTMAX = OPTIMIZE and os.environ.get("REMOVE_LAST_SOFTMAX", "0") == "1"
AFFINE_CONCAT = OPTIMIZE and os.environ.get("AFFINE_CONCAT", "1") == "1"
CONCAT_SGEMM_BIAS = OPTIMIZE and os.environ.get("CONCAT_SGEMM_BIAS", "1") == "1"
COMBINE_AFFINE_TRANSFORM = OPTIMIZE and os.environ.get("OPTIMIZE_AFFINE_TRANSFORM", "1") == "1"

# memory allocation
VALIDATE_GENERATED_SOURCE = OPTIMIZE and os.environ.get("VALIDATE_GENERATED_SOURCE", "1") == "1"
OPTIMIZE_INPLACE_OPERATION = OPTIMIZE and os.environ.get("OPTIMIZE_INPLACE_OPERATION", "1") == "1"
VISUALIZE_MEMORY_ALLOCATION = OPTIMIZE and os.environ.get("VISUALIZE_MEMORY_ALLOCATION", "0") == "1"
OPTIMIZE_MEMORY_ALLOCATION = OPTIMIZE and os.environ.get("OPTIMIZE_MEMORY_ALLOCATION", "1") == "1"

# kernel generation
EMBED_METABUFFER_VALUE = OPTIMIZE and os.environ.get("EMBED_METABUFFER_VALUE", "0") == "1"
