// Compile WGSL shader sources into a single TypeScript module.
// Reads src/shader/webgpu/shadersources/standard/*.wgsl and emits
// src/descriptor_runner/operators/webgpu/shaders.ts as Record<string, string>.
const fs = require("fs");
const path = require("path");

const sourcesDir = path.join(__dirname, "shadersources", "standard");
const outPath = path.join(
  __dirname,
  "..",
  "..",
  "descriptor_runner",
  "operators",
  "webgpu",
  "shaders.ts"
);

let out = "/* eslint-disable */\n";
out += "// auto-generated by src/shader/webgpu/compile.js from *.wgsl sources\n";
out += "export const webgpuShaders: Record<string, string> = {\n";

for (const file of fs.readdirSync(sourcesDir).sort()) {
  if (!file.endsWith(".wgsl")) continue;
  const name = file.replace(/\.wgsl$/, "");
  const src = fs.readFileSync(path.join(sourcesDir, file), "utf-8");
  out += `  ${JSON.stringify(name)}: ${JSON.stringify(src)},\n`;
}

out += "};\n";
fs.writeFileSync(outPath, out);
console.log("wrote", outPath);
